---
title: "Dealing with Git Branching"
author: "Brennen Long"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Little Birds are dining  
Warily and well,  
Hid in mossy cell:  
Hid, I say, by waiters  
Gorgeous in their gaiters -  
I've a Tale to tell.  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
That was a thing we could not wait to learn.   
We saw the risk we took in doing good,   
But dared not spare to do the best we could   
Though harm should come of it; so built the screen   
You had begun, and gave them back their shade.  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
  
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I find no peace, and all my war is done.  
I fear and hope. I burn and freeze like ice.  
I fly above the wind, yet can I not arise;  
And nought I have, and all the world I seize on.  
That loseth nor locketh holdeth me in prison  
And holdeth me not—yet can I scape no wise—  
Nor letteth me live nor die at my device,  
And yet of death it giveth me occasion.  
Without eyen I see, and without tongue I plain.  
I desire to perish, and yet I ask health.  
  